In [23]:
import torch

In [24]:
# 📌 문제 1: PyTorch에서 랜덤 텐서를 생성하고, 가장 큰 값을 가진 인덱스를 찾으세요.

# (1) 4x4 크기의 랜덤 텐서를 생성하세요.
x = torch.rand(4,4)
print(x)
# (2) 각 행에서 가장 큰 값을 가진 인덱스를 찾으세요.
max_indices = torch.argmax(x, dim=1)
print(max_indices)

tensor([[0.9914, 0.1278, 0.4724, 0.8482],
        [0.1247, 0.1916, 0.0437, 0.7368],
        [0.6733, 0.6197, 0.9376, 0.3216],
        [0.4149, 0.8519, 0.9634, 0.8013]])
tensor([0, 3, 2, 2])


In [25]:
# 📌 문제 2: squeeze()와 unsqueeze()를 이용해 텐서의 차원을 조작하세요.
#
# # (1) (1, 3, 1, 4) 크기의 랜덤 텐서를 생성하세요.
x = torch.rand(1,3,1,4)
# # (2) squeeze()를 사용하여 크기를 줄이세요.
x_squeezed = x.squeeze()
print(x_squeezed.shape)
# # (3) unsqueeze()를 사용하여 특정 차원에 새 차원을 추가하세요.
x_unsqueezed = x_squeezed.unsqueeze_(1)
print(x_unsqueezed.shape)

torch.Size([3, 4])
torch.Size([3, 1, 4])


In [26]:
# 📌 문제 3: torch.cat()과 torch.stack()의 차이를 확인하세요.
# (1) 크기가 (2,3)인 두 개의 텐서를 만드세요.
a = torch.tensor([[1,2,3],[4,5,6]])
b = torch.tensor([[7,8,9],[10,11,12]])
# (2) torch.cat()을 이용하여 dim=0 방향으로 연결하세요.
cat_result = torch.cat([a,b], dim=0)
print(cat_result)
print(cat_result.shape)
# (3) torch.stack()을 이용하여 dim=0 방향으로 스택하세요.
stack_result = torch.stack([a,b], dim=0)
print(stack_result)
print(stack_result.shape)


tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])
torch.Size([4, 3])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])
torch.Size([2, 2, 3])


In [27]:
# 📌 문제 4: torch.index_select()를 이용해 특정 행/열을 선택하세요.

# (1) 크기가 (4,4)인 랜덤 텐서를 생성하세요.
x = torch.rand(4, 4)
print("원본 텐서:\n", x)
# (2) 첫 번째 열과 세 번째 열을 선택하여 새로운 텐서를 만드세요.
indices = torch.tensor([0, 2])
selected_cols = torch.index_select(x, dim=1, index=indices)
print("선택된 열들:\n", selected_cols)

원본 텐서:
 tensor([[0.6825, 0.2197, 0.9470, 0.5651],
        [0.0855, 0.6317, 0.3094, 0.8574],
        [0.6824, 0.0600, 0.0879, 0.2095],
        [0.5460, 0.3745, 0.9605, 0.6643]])
선택된 열들:
 tensor([[0.6825, 0.9470],
        [0.0855, 0.3094],
        [0.6824, 0.0879],
        [0.5460, 0.9605]])


In [28]:
# 📌 문제 5: torch.topk()와 masked_fill()을 조합하여
# 특정 조건을 만족하는 값을 변경하세요.

# (1) 크기가 (3,5)인 랜덤 텐서를 생성하세요.
x = torch.rand(3, 5)
print("원본 텐서:\n", x)
# (2) 각 행에서 상위 3개의 값만 유지하고 나머지는 0으로 채우세요.
values, indices = torch.topk(x, k=3, dim=1)
#(3) 나머지 모든 원소는 0으로 만들고, 상위 3개만 위치만 유지.
# scatter_(1, indices, 1), 1 : 열기준으로 값을 할당,
# 찾은 위치의 값 할당,
# 1 : 해당 위치에 1로 값을 변경.
mask = torch.zeros_like(x).scatter_(1, indices, 1)
masked_x = x * mask
print("상위 3개 값만 유지된 텐서:\n", masked_x)

원본 텐서:
 tensor([[0.5520, 0.7762, 0.7653, 0.0819, 0.8706],
        [0.7512, 0.5262, 0.6345, 0.4765, 0.4052],
        [0.8744, 0.8653, 0.9097, 0.1491, 0.7867]])
상위 3개 값만 유지된 텐서:
 tensor([[0.0000, 0.7762, 0.7653, 0.0000, 0.8706],
        [0.7512, 0.5262, 0.6345, 0.0000, 0.0000],
        [0.8744, 0.8653, 0.9097, 0.0000, 0.0000]])


In [29]:
# 📌 문제 6: torch.randperm()을 이용하여 데이터를 랜덤하게 섞은 후,
# torch.chunk()로 나누세요.
#
# (1) 10개의 원소를 가진 텐서를 0~9까지 숫자로 채우세요.
x = torch.arange(10)
print("원본 텐서:", x)

# (2) `torch.randperm()`을 사용하여 무작위로 섞으세요.
shuffled_x = x[torch.randperm(10)]
print("섞인 텐서:", shuffled_x)
# (3) `torch.chunk()`를 사용하여 2개의 부분으로 나누세요.
chunks = torch.chunk(shuffled_x, chunks=2)
print("첫 번째 부분:", chunks[0])
print("두 번째 부분:", chunks[1])

원본 텐서: tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
섞인 텐서: tensor([5, 6, 1, 4, 0, 2, 9, 3, 7, 8])
첫 번째 부분: tensor([5, 6, 1, 4, 0])
두 번째 부분: tensor([2, 9, 3, 7, 8])


In [30]:
# 📌 문제 7: expand()를 사용하여 텐서 크기를 확장하세요.

# (1) 크기가 (1, 3)인 텐서를 생성하세요.
x = torch.tensor([[1, 2, 3]])  # Shape: (1,3)
print("원본 텐서:\n", x)
# (2) `expand()`를 사용하여 (5, 3) 크기로 확장하세요.
expanded_x = x.expand(5, 3)
print("expand() 적용 후:\n", expanded_x)


원본 텐서:
 tensor([[1, 2, 3]])
expand() 적용 후:
 tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])


In [31]:
# 📌 문제 8: split()과 chunk()의 차이를 이해하세요.
#
# (1) 크기가 (10,)인 1D 텐서를 생성하세요.
x = torch.arange(10)
print("원본 텐서:", x)
# (2) `split()`을 사용하여 3개의 텐서로 나누세요.
split_result = torch.split(x, [3, 3, 4])
print("split() 결과:", split_result)
# (3) `chunk()`을 사용하여 3개의 텐서로 나누세요.
chunk_result = torch.chunk(x, chunks=3)
print("chunk() 결과:", chunk_result)

원본 텐서: tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
split() 결과: (tensor([0, 1, 2]), tensor([3, 4, 5]), tensor([6, 7, 8, 9]))
chunk() 결과: (tensor([0, 1, 2, 3]), tensor([4, 5, 6, 7]), tensor([8, 9]))


In [32]:
# 📌 문제 9: masked_fill()을 사용하여 특정 조건을 만족하는 요소를 변경하세요.

# (1) 크기가 (3, 3)인 랜덤 텐서를 생성하세요.
x = torch.rand(3, 3)
print("원본 텐서:\n", x)

# (2) 값이 0.5보다 작은 요소를 -1로 변경하세요.
masked_x = x.masked_fill(x < 0.5, -1)
print("masked_fill() 적용 후:\n", masked_x)


원본 텐서:
 tensor([[0.7494, 0.8215, 0.1657],
        [0.2160, 0.6427, 0.1532],
        [0.8059, 0.2420, 0.5358]])
masked_fill() 적용 후:
 tensor([[ 0.7494,  0.8215, -1.0000],
        [-1.0000,  0.6427, -1.0000],
        [ 0.8059, -1.0000,  0.5358]])


In [33]:
# 📌 문제 10: torch.index_select()를 이용하여 특정 행을 선택하세요.
#
# (1) 크기가 (5, 4)인 랜덤 텐서를 생성하세요.
x = torch.rand(5, 4)
print("원본 텐서:\n", x)

# (2) 두 번째와 네 번째 행만 선택하세요.
indices = torch.tensor([1, 3])
selected_rows = torch.index_select(x, dim=0, index=indices)
print("선택된 행들:\n", selected_rows)

원본 텐서:
 tensor([[0.6408, 0.8483, 0.2052, 0.0337],
        [0.3043, 0.3742, 0.2450, 0.4660],
        [0.4244, 0.3120, 0.8635, 0.3524],
        [0.3663, 0.3223, 0.0154, 0.0703],
        [0.6525, 0.3289, 0.1172, 0.8535]])
선택된 행들:
 tensor([[0.3043, 0.3742, 0.2450, 0.4660],
        [0.3663, 0.3223, 0.0154, 0.0703]])
